version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
    steps:
      - codecov/upload:
          file: {{ coverage_report_filepath }}

orbs:
  maven: circleci/maven@1.0.0
  codecov: codecov/codecov@1.0.2

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
